FROM python:3.11-slim

WORKDIR /app

COPY ./backend/app /app/app
COPY ./backend/alembic /app/alembic
COPY ./backend/alembic.ini /app/alembic.ini

RUN pip install --no-cache-dir \
  fastapi \
  uvicorn[standard] \
  sqlalchemy \
  alembic \
  psycopg2-binary \
  python-jose \
  passlib \
  pydantic \
  pydantic-settings \
  email-validator

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
